### ISSUE TITLE
/help triggered multiple times (after redeploy)

### ISSUE THREAD

**Issue by mrummuka** [windkh/node-red-contrib-telegrambot#9] opened 2016-11-13 15:01 UTC
Hi,

I'm having trouble with setting up a simple flow that would support both simple /help command (displaying a help message) and one simple operation that gets triggered by an input received by  TelegramReceiver.

It seems like the TelegramReceiver / Telegram command obtains the same message (same message ID, same chat ID) multiple times, despite that was only entered once to the chat. This causes e.g. /help command to reply 2 - 4 times whenever it is triggered.

Has anyone else noticed this kind of occurrence?

**Comment by windkh** [comment] 2016-11-13 15:08
This could happen if you have more than one configuration node with the same token.

**Comment by mrummuka** [comment] 2016-11-13 15:12
Hmm. That seems not to be the case, since I specifically created the new token for this flow.

**Comment by mrummuka** [comment] 2016-11-13 15:19
Hmm. Interestingly enough, it seems like this was caused by the 'rbe' node that I had as part of the flow which somehow caused the described behaviour. Currently, after removing that I don't seem to be able to trigger the same problem occurring any longer. Therefore, closing this for the time being.

**Comment by windkh** [comment] 2016-11-18 20:50
What is a 'rbe' node?

**Comment by mrummuka** [comment] 2016-11-20 07:52
'rbe' = https://www.npmjs.com/package/node-red-node-rbe, i.e. a module/node that I tried to use to solve the problem encountered.

However, I think that I closed the issue too hastily as ever since (without any rbe nodes in the flow :) ) I have encountered similar situations with TelegramReceiver (and TelegramSender) nodes.

I haven't yet had time to debug it further but somehow I get situations where the incoming message (with same chatid and messageid) is received multiple (so far between 2..6) times and therefore gets also processed as many times by the node-red flow.

**Comment by windkh** [comment] 2016-11-20 08:48
That is strange. I remember having the same problem in the beginning of the development of the telegram nodes. Does the problem arise right after starting nodered or after having downloaded changes in your flow several times?

**Comment by mrummuka** [comment] 2017-06-04 09:08
It seems I haven't noted your question, but now that I encountered the issue again, I think it more or less both. So I got the situation reintroduced by
- creating  a new flow 
- inserting Telegram Receiver and Telegram Command and Telegram Sender nodes in it (all with same configuration, that wasn't previously available)
- Configuring them and trying to run /help

Note: If it helps to debug the issue, I do have other flows in same node-red instance with telegram receiver/sender but using different bots.

**Comment by windkh** [comment] 2017-06-04 09:11
I'll try to reproduce this

**Comment by windkh** [comment] 2017-06-04 12:29
Could you send me a sample flow?

**Comment by mrummuka** [comment] 2017-06-04 12:47
Sure. Created just for this.

[{"id":"c7a99651.8786c","type":"telegram receiver","z":"ff6510b3.6c831","name":"","bot":"4b4a9785.43a61","saveDataDir":"","x":194.5,"y":111.5,"wires":[["61ab92fd.8a3b5c","109b0cbd.783a0b","7cdf3ee4.66c87"],[]]},{"id":"7ca49968.45097","type":"telegram command","z":"ff6510b3.6c831","name":"help","command":"/help","bot":"4b4a9785.43a61","x":193.5,"y":208.5,"wires":[["5641023c.b46f2c","109b0cbd.783a0b"],[]]},{"id":"7cdf3ee4.66c87","type":"function","z":"ff6510b3.6c831","name":"createChatMsg","func":"var data = msg.payload\nmsg.payload = {}\n\nvar chatId = flow.get('chatId')||0;\nmsg.payload.chatId = chatId;\nmsg.payload.content = data\nmsg.payload.type = 'message';\nmsg.payload.options = {disable_web_page_preview : true};\n\nreturn msg;\n","outputs":1,"noerr":0,"x":810,"y":129,"wires":[["5457e91b.4cb7d"]]},{"id":"5457e91b.4cb7d","type":"telegram sender","z":"ff6510b3.6c831","name":"","bot":"4b4a9785.43a61","x":859.5,"y":179.5,"wires":[[]]},{"id":"61ab92fd.8a3b5c","type":"debug","z":"ff6510b3.6c831","name":"","active":true,"console":"false","complete":"true","x":564,"y":99,"wires":[]},{"id":"5641023c.b46f2c","type":"function","z":"ff6510b3.6c831","name":"show help","func":"if (typeof msg.payload === \"undefined\" || msg.payload === null) {\n    node.warn(\"Empty name\")\n    msg.payload = null;\n    return msg;\n}\n\nmsg.payload = \"FtfWatcher sends pb notifications also via Telegram\\n\";\nreturn msg;\n","outputs":1,"noerr":0,"x":520,"y":213,"wires":[["7cdf3ee4.66c87"]]},{"id":"782ed2e5.171254","type":"function","z":"ff6510b3.6c831","name":"set flow.botstatus","func":"//Turn on\nflow.set('botstatus',1);\nmsg.payload(\"Bot turned on\")\nreturn msg;","outputs":1,"noerr":0,"x":538,"y":256.5,"wires":[["7cdf3ee4.66c87"]]},{"id":"5d86289.e0c48d8","type":"function","z":"ff6510b3.6c831","name":"set flow.botstatus","func":"//Turn off\nflow.set('botstatus',0);\nmsg.payload(\"Bot turned off\")\nreturn msg;","outputs":1,"noerr":0,"x":537,"y":298,"wires":[["7cdf3ee4.66c87"]]},{"id":"109b0cbd.783a0b","type":"function","z":"ff6510b3.6c831","name":"store chatId","func":"if (typeof msg.payload === \"undefined\" || msg.payload === null) {\n    node.warn(\"Empty name\")\n    msg.payload = null;\n    return msg;\n}\nvar chat = msg.payload.chatId;\n// store the chatId to flow context\nflow.set('chatId',chat);\nreturn msg;\n","outputs":1,"noerr":0,"x":455,"y":427.5,"wires":[[]]},{"id":"42ea703a.e094d8","type":"telegram command","z":"ff6510b3.6c831","name":"turnoff","command":"/turnoff","bot":"4b4a9785.43a61","x":198,"y":309,"wires":[["5d86289.e0c48d8"],[]]},{"id":"921b57e3.81d26","type":"telegram command","z":"ff6510b3.6c831","name":"turnon","command":"/turnon","bot":"4b4a9785.43a61","x":189,"y":255,"wires":[["782ed2e5.171254"],[]]},{"id":"4b4a9785.43a61","type":"telegram bot","z":"ff6510b3.6c831","botname":"alksjdflkasjdfBot","usernames":"","chatids":""}]

**Comment by windkh** [comment] 2017-06-04 12:48
Thnx

Gesendet mit der WEB.DE iPad App

Am 04.06.17 um 14:47 schrieb Mika Rummukainen

**Comment by mrummuka** [comment] 2017-06-04 13:04
Also please note that it didn't occur straight at the first time, only after I had also entered something else (msg history attached as well). 


![screenshot from 2017-06-04 15-59-24](https://cloud.githubusercontent.com/assets/14860687/26761828/6bf12f34-493f-11e7-89b4-04fa2e127ac7.png)
![screenshot from 2017-06-04 15-59-47](https://cloud.githubusercontent.com/assets/14860687/26761833/722e5aca-493f-11e7-9010-999d183dfd64.png)

**Comment by windkh** [comment] 2017-06-04 13:07
Very strange indeed

**Comment by windkh** [comment] 2017-06-04 14:48
I can't reproduce the problem. Node-Red refused to import your flow. So I created the nodes manually. Could you please verify if the nodes look like yours?
`
[{"id":"37d87796.2544b8","type":"telegram receiver","z":"725879df.541168","name":"","bot":"ccc4a708.ce4228","saveDataDir":"","x":145.16669464111328,"y":93.33334922790527,"wires":[["53038350.122fcc","efa6dec0.5832c","5e0ed1db.6815b"],[]]},{"id":"3a879220.83c18e","type":"telegram command","z":"725879df.541168","name":"/help","command":"/help","bot":"ccc4a708.ce4228","x":103.16670227050781,"y":163.33337020874023,"wires":[["cdccf234.558b","5e0ed1db.6815b"],[]]},{"id":"53038350.122fcc","type":"function","z":"725879df.541168","name":"createChatMsg","func":"var data = msg.payload\nmsg.payload = {}\n\nvar chatId = flow.get('chatId')||0;\nmsg.payload.chatId = chatId;\nmsg.payload.content = data\nmsg.payload.type = 'message';\nmsg.payload.options = {disable_web_page_preview : true};\n\nreturn msg;\n","outputs":1,"noerr":0,"x":683.1667327880859,"y":127.00001811981201,"wires":[["8522608.f55aba"]]},{"id":"8522608.f55aba","type":"telegram sender","z":"725879df.541168","name":"","bot":"ccc4a708.ce4228","x":899.1667022705078,"y":123.33335304260254,"wires":[[]]},{"id":"efa6dec0.5832c","type":"debug","z":"725879df.541168","name":"","active":true,"console":"false","complete":"false","x":361.1666946411133,"y":62.66667556762695,"wires":[]},{"id":"cdccf234.558b","type":"function","z":"725879df.541168","name":"show help","func":"if (typeof msg.payload === \"undefined\" || msg.payload === null) {\n    node.warn(\"Empty name\")\n    msg.payload = null;\n    return msg;\n    \n}\nmsg.payload = \"FtfWatcher sends pb notifications also via Telegram\\n\";\nreturn msg;\n","outputs":1,"noerr":0,"x":345.16670989990234,"y":211.00005626678467,"wires":[["53038350.122fcc"]]},{"id":"2ce2cdc.484ca32","type":"function","z":"725879df.541168","name":"set flow.botstatus","func":"//Turn on\nflow.set('botstatus',1);\nmsg.payload = \"Bot turned on\";\nreturn msg;","outputs":1,"noerr":0,"x":373.1666946411133,"y":323.0000591278076,"wires":[["53038350.122fcc"]]},{"id":"dd9771a9.efbbf","type":"function","z":"725879df.541168","name":"set flow.botstatus","func":"//Turn off\nflow.set('botstatus',0);\nmsg.payload= \"Bot turned off\";\nreturn msg;\n","outputs":1,"noerr":0,"x":375.1667175292969,"y":373.0000629425049,"wires":[["53038350.122fcc"]]},{"id":"5e0ed1db.6815b","type":"function","z":"725879df.541168","name":"store chatId","func":"if (typeof msg.payload === \"undefined\" || msg.payload === null) {\n    node.warn(\"Empty name\")\n    msg.payload = null;\n    return msg;\n    \n}\nvar chat = msg.payload.chatId;\n// store the chatId to flow context\nflow.set('chatId',chat);\nreturn msg;\n","outputs":1,"noerr":0,"x":355.1667060852051,"y":161.0000400543213,"wires":[[]]},{"id":"149aa5f7.e4ffaa","type":"telegram command","z":"725879df.541168","name":"turnoff","command":"/turnoff","bot":"ccc4a708.ce4228","x":111.16668701171875,"y":377.3333511352539,"wires":[["dd9771a9.efbbf"],[]]},{"id":"675044ac.1c8aec","type":"telegram command","z":"725879df.541168","name":"turn on","command":"/turnon","bot":"ccc4a708.ce4228","x":111.16668319702148,"y":327.33336713910103,"wires":[["2ce2cdc.484ca32"],[]]},{"id":"ccc4a708.ce4228","type":"telegram bot","z":"","botname":"blablablaBot","usernames":"","chatids":""}]
`
The turnoff and turnon functions nodes had to be adapted as msg.payload("Bot turned on") is not a function.
<img width="377" alt="noderedfunction" src="https://cloud.githubusercontent.com/assets/10910767/26762605/62953b96-4945-11e7-9bef-983e2e11419c.png">

The flow looks like
<img width="745" alt="noderedflow" src="https://cloud.githubusercontent.com/assets/10910767/26762607/6a10456e-4945-11e7-9252-2bfad85851ef.png">

And the result in the chat looks like:
<img width="300" alt="noderedchat" src="https://cloud.githubusercontent.com/assets/10910767/26762619/8ef90e56-4945-11e7-88e6-f7c268c35f28.png">

Sorry but I can't reproduce the problem right now. Please provide further information.

**Comment by windkh** [comment] 2017-06-04 17:52
What node-red/nodejs version do you use?

**Comment by mrummuka** [comment] 2017-06-04 17:56
Interesting, really. My versions below and my flow (screen capture) below so it should be the same. 

I still wonder why the import failed on your side (haven't had time to test yours)
![screenshot from 2017-06-04 20-55-11](https://cloud.githubusercontent.com/assets/14860687/26764062/229e451e-4968-11e7-9011-c2adc2308adc.png)


4 Jun 12:29:33 - [info] Node-RED version: v0.14.6
4 Jun 12:29:33 - [info] Node.js  version: v4.2.6
4 Jun 12:29:33 - [info] Linux 4.4.0-31-generic x64 LE

**Comment by windkh** [comment] 2017-06-04 18:17
I am using the desktop version of telegram, too. 
Windows 7
Node 6.10.1
Node-red 0.16.2

**Comment by mrummuka** [comment] 2017-06-04 18:27
OK, then it's not that.

I now imported your flow (interestingly, no problems in that) and tested and it worked. At first. But now I think I know how to reproduce this more specifically since I got it again to reproduce quite quickly.

First, no problems with the flow even after the first redeployment. 
But after second deployment the same problems reoccurred immediately.

My guess would be that either because I was typing at the same time while the second deploy was still ongoing (node-red/telegram was not fully initialized?) or because of the deletion I made to the flow (not likely as I'm pretty sure you can once again do the deletion without problems ). 

Here are the exact steps what I did to make it occur again.
![screenshot from 2017-06-04 21-23-02](https://cloud.githubusercontent.com/assets/14860687/26764251/52d9927a-496c-11e7-8878-9007935983b8.png)

**Comment by windkh** [comment] 2017-06-04 18:41
Redeploying the same flow could lead to the problems you described. I don't know where it really comes from. But I asume that the there is a problem with stopping and restarting the underlying api. Under normal circumstances it should work,  but sometimes not. As a workaround you could restart node-red to make sure that the zombie instance is gone. But as I said. Right now I don't have any idea how to get around this.

**Comment by mrummuka** [comment] 2017-06-04 18:50
OK, then I'll try to keep that in mind and ensure somehow that the bot is not used before the deployment is complete initialized.

**Comment by windkh** [comment] 2017-06-04 19:31
I'll try to find a solution...

**Comment by windkh** [comment] 2017-06-04 20:03
Please try 2.4.0 and have a look at the warnings in the console, as I added some further tracings in the code.

**Comment by windkh** [comment] 2017-06-04 21:25
Hm I found a strange thing in your flow:
The receiver sends its content directly to the createChatMsg function node. There the content is stored in the local variable data and reused as new content when sending a message. Now you have the receiver node's message object in the content of the message you are going to send away!

I guess you intended to have some string here (see help turnoff and turnon nodes), but in this case (receiver node) its an object. Maybe this leads to some unpredictable behavior.

![image](https://cloud.githubusercontent.com/assets/10910767/26765475/11d38cf2-497d-11e7-96ec-d8fcd277fe3d.png)

**Comment by mrummuka** [comment] 2017-06-05 05:17
Hi,
OK - I now think that I understand what you found to be strange. That seems
to be an error in my side, although, perhaps the telegram sender could also
notify/warn the user from doing stupid user mistakes such as using
unexpected input data? :)

My intention in this testing flow was simply to
* echo all messages back by the bot it receives (apart from commands used
by telegram command nodes).
* create one command /help that would send some information to user
* enable user to switch bot on/off by command (with off in this context I
mean that the bot does not send anything to the user apart from ACK to
user's "turnon" command)

The turnon/turnoff nodes are not yet functional, but it's just a matter of
one filter in front of createChatMsg.

So, I guess I should have connected receiver directly to sender and not
like it is currently. Thanks for pointing this out, I'll see if it changes
any behaviour

Br,
Mika


ma 5. kesäk. 2017 klo 0.25 windkh <notifications@github.com> kirjoitti:

**Comment by mrummuka** [comment] 2017-06-05 05:18
Unfortunately 2.4.0 seems to break my system (no longer answers from bot) with 
5 Jun 04:50:40 - [error] [telegram sender:fd15ab38.f3199] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram receiver:e247e3de.698ee] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram receiver:c7a99651.8786c] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram command:7ca49968.45097] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram sender:5457e91b.4cb7d] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram command:42ea703a.e094d8] TypeError: self.nodes.includes is not a function
5 Jun 04:50:40 - [error] [telegram command:921b57e3.81d26] TypeError: self.nodes.includes is not a function
errors in the log when node-red is starting.

**Comment by windkh** [comment] 2017-06-05 06:21
I'll replace the includes call and ship a new version

**Comment by windkh** [comment] 2017-06-05 06:55
includes is part of ECMAScript2016. Sorry I missed that. 2.4.1 should work.

**Comment by aniston** [comment] 2017-08-08 14:50
@windkh 
I have the same problem described by @mrummuka and it is quite simple to replicate.

First my versions are as follows:
8 Aug 16:25:10 - [info] Node-RED version: v0.17.5
8 Aug 16:25:10 - [info] Node.js  version: v6.11.2
8 Aug 16:25:10 - [info] Linux 4.4.0-89-generic x64 LE
and the node-red-contrib-telegrambot 2.5.0

quite simply with a Telegram Receiver node connected to an Output Debug node and a configured Token Bot, at first it works without doppelt request messages ie: only one reply (doesn't matter if the /request comes from Telegram desktop or Android client or Web.telegram.org) and can be deployed successfully many times without problems.

- Problem starts after deleting the Telegram Receiver node and Deploying and this can be seen instantly by sending another command via the bot which gets received by node-red-contrib-telegrambot even though no Receiver is in use !

- Now adding again the Telegram Receiver cause 2 reception messages one with "msg.payload.content" and one without or rather an empty "msg.payload.content", however the content is always doubled in  "msg.originalMessage.chat.text" and so we get 2 Telegrams !

What seems to be the problem is between the clearing of a node flow when the Telegram Receiver is deleted for example and still the debug receives the message , hence the Receiver is not really cleared or deleted from the flow, so reimplementing it makes 2 of them !

HTH.

**Comment by aniston** [comment] 2017-08-08 15:32
@mrummuka , @windkh , as a temporary solution, I have found that Deploy Full cures and does not cause the doubling/tripling effect as noticed before. @mrummuka I said cures as it can wipe off the double effect caused created with a Deploy Modified Flows , can you please check that ?

Downside is that Deploy Full deploys all flow again and on my virtual system takes between 6 ~ 8 seconds every time i Deploy Full against 2 ~ 3 seconds of  Deploy Modified Flows.

@windkh , I do not know what the flow clearing logic is different between or against Delpoy Full and  Deploy Modified Flows, but I guess that is a good clue as to what is happening behind the node-red Flows layering and your contrib node.

PS: i used the flow provided above by windk on 4 Jun as my test flow.

**Comment by windkh** [comment] 2017-08-11 11:20
Ok thanks for this hint. I will have a look at it soon!

**Comment by AxelRHD** [comment] 2018-01-11 20:54
Having the same problem here. Multiple replies, also on wrong commands.

**Comment by windkh** [comment] 2018-03-31 19:19
Version 3.1.0 finally should fix this issue. Sorry guys that it took so long.

**Comment by windkh** [comment] 2022-02-15 20:31
@javiermoro 
did you do a full redeploy? 
try restarting node-red to make sure no zombie is lurking in your memory

**Comment by javiermoro** [comment] 2022-02-15 20:39
Hi @windkh 

yes, full redeploy, node-red restart, even home-assistant blue restarted.

**Comment by windkh** [comment] 2022-02-15 20:40
What platform? Do you have more than one config node?

**Comment by javiermoro** [comment] 2022-02-15 20:42
Is this what you need?

15 Feb 21:38:36 - [info] Node-RED version: v2.2.0
15 Feb 21:38:36 - [info] Node.js  version: v16.14.0
15 Feb 21:38:36 - [info] Linux 5.10.98 arm64 LE

**Comment by windkh** [comment] 2022-02-15 20:47
Are you able to debug using e.g. visual code or any other js debugger?

**Comment by javiermoro** [comment] 2022-02-15 20:51
If you can guide me, maybe I can help you. I have vscode installed.

**Comment by windkh** [comment] 2022-02-15 20:57
Node red under windows?

**Comment by javiermoro** [comment] 2022-02-15 20:59
No its a linux system.

**Comment by windkh** [comment] 2022-02-15 21:09
Then maybe it is the best that you export your flow and send it to me via email.
I can have a look at it tomorrow. And please check first that you do not have two help nodes in the same flow or in another tab.

**Comment by javiermoro** [comment] 2022-02-16 08:12
Hi @windkh 

I think that I found the problem. I don't know how this happened, but the output from the command node had two wires to the next one. This caused the message to be sended twice to telegram.

```
[
    {
        "id": "93236209a95bd84b",
        "type": "telegram command",
        "z": "12c41db77360c6f4",
        "name": "Help",
        "command": "/ayuda",
        "description": "Opciones del bot",
        "registercommand": true,
        "language": "",
        "scope": "default",
        "bot": "cbccb48fadb7774f",
        "strict": false,
        "hasresponse": true,
        "useregex": false,
        "removeregexcommand": false,
        "outputs": 2,
        "x": 110,
        "y": 280,
        "wires": [
            [
                "367773de993edca9",
                "367773de993edca9"
            ],
            []
        ]
    },
   
```
I think that you can close this issue.

Thanks for your help.

**Closed** 2022-02-16 12:39 UTC
