### ISSUE TITLE
Can't get rid from Custom keyboard

### ISSUE THREAD

**Issue by Barabba11** [windkh/node-red-contrib-telegrambot#288] opened 2023-01-04 20:09 UTC
Hi, I've followed the example, in particular I'm sure I added context.global.keyboard.pending=false; on the function node attached to the second output of telegram command module, but I can't kill it, it still in the chat until I delete the bot, if I rejoin it and launch a command it will appear and keep there, doesn't matter how many times I press the 2 options, or if I execute the same or another command. The command actually works and produce the desidered result, it just doesn't remove the keyboard. Is it a bug? In previous time with the same functions nodes I haven't this problem

**Comment by Barabba11** [comment] 2023-01-05 11:43
a bit strange, I'm sending the same message to two different chatId, I receive the confermation message on both, it means the function node containing context.global.keyboard.pending=false;  has been executed, initally I have the same problem on both phones about steady Keyboard, but after some time on one phone it disappear, on the other persist.

**Comment by windkh** [comment] 2023-01-24 22:46
please send me your flow

**Comment by windkh** [comment] 2023-02-04 16:27
@Barabba11  hi, as the problem is on the client side I would like to close this one, ok?

**Closed by windkh** 2023-02-04 16:27 UTC
