### ISSUE TITLE
type photo: EFATAL: TypeError [ERR_INVALID_CHAR]

### ISSUE THREAD

**Issue by OKDaG** [windkh/node-red-contrib-telegrambot#215] opened 2021-10-01 19:43 UTC
Hi,
i'm running nodered v2.0.6 with node-red-contrib-telegrambot v10.0.7 and wanted to send a photo with Telegram Sender but got this error:

msg.payload: object
{"chatId":279600xxx,"type":"photo","content":"/tmp/cam.jpg","caption":"Hof"}

msg.string[349]
Caught exception in sender node:
Error: EFATAL: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["getKeyByValue"]
when processing message: 
{"_msgid":"e06280de37aaa560","payload":{"chatId":279600xxx,"type":"photo","content":"/tmp/cam.jpg","caption":"Hof","options":{"caption":"Hof","chat_id":279600xxx,"photo":null}},"topic":""}

Any hints?

**Comment by windkh** [comment] 2021-10-02 05:59
Thanks for reporting. I have never seen this before. Is it reproducable?
Can you send me the flow with an example photo via email?

**Comment by OKDaG** [comment] 2021-10-02 07:10
[
    {
        "id": "96f77d076a52f9a7",
        "type": "inject",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 170,
        "y": 520,
        "wires": [
            [
                "1b6e18b0c16520ba"
            ]
        ]
    },
    {
        "id": "1b6e18b0c16520ba",
        "type": "http request",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "method": "GET",
        "ret": "bin",
        "paytoqs": "ignore",
        "url": "https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg",
        "tls": "",
        "persist": false,
        "proxy": "",
        "authType": "",
        "x": 370,
        "y": 520,
        "wires": [
            [
                "dd38153198a762ec",
                "c018db46f8e21c08"
            ]
        ]
    },
    {
        "id": "dd38153198a762ec",
        "type": "file",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "filename": "/tmp/test.jpg",
        "appendNewline": false,
        "createDir": false,
        "overwriteFile": "true",
        "encoding": "none",
        "x": 570,
        "y": 520,
        "wires": [
            [
                "3bbe515a2e0f8c10"
            ]
        ]
    },
    {
        "id": "3bbe515a2e0f8c10",
        "type": "function",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "func": "\nvar pl = {\n  content: '/tmp/test.jpg',\n  type : 'photo',\n  chatId: 279600xxx\n}\n\nmsg.payload = pl;\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 760,
        "y": 520,
        "wires": [
            [
                "90e8af0dac58027f"
            ]
        ]
    },
    {
        "id": "90e8af0dac58027f",
        "type": "telegram sender",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "bot": "0385f759deab4c2f",
        "haserroroutput": false,
        "outputs": 1,
        "x": 960,
        "y": 520,
        "wires": [
            []
        ]
    },
    {
        "id": "c018db46f8e21c08",
        "type": "image",
        "z": "f6f2187d.f17ca8",
        "name": "",
        "width": 160,
        "data": "payload",
        "dataType": "msg",
        "thumbnail": false,
        "active": true,
        "pass": false,
        "outputs": 0,
        "x": 580,
        "y": 560,
        "wires": []
    },
    {
        "id": "0385f759deab4c2f",
        "type": "telegram bot",
        "botname": "nrbot.fra",
        "usernames": "",
        "chatids": "",
        "baseapiurl": "",
        "updatemode": "polling",
        "pollinterval": "300",
        "usesocks": false,
        "sockshost": "",
        "socksport": "6667",
        "socksusername": "anonymous",
        "sockspassword": "",
        "bothost": "",
        "botpath": "",
        "localbotport": "8443",
        "publicbotport": "8443",
        "privatekey": "",
        "certificate": "",
        "useselfsignedcertificate": false,
        "sslterminated": false,
        "verboselogging": false
    }
]

**Comment by OKDaG** [comment] 2021-10-02 07:12
this loads an external jpg from wikimedia, result is the same error without sending the image

**Comment by windkh** [comment] 2021-10-02 21:29
I just tried your flow. It works here. Well I had to change the path to "c:/temp/test.jpg" because I am running under windows.
So basically the image is ok and the flow, too.
The only thing left is the file on the harddisc.
Can you directly send the image without accessing the harddisc by just assigning the image buffer to content as follows
content: msg.payload,

see also https://discourse.nodered.org/t/taking-a-picture-and-sending-it-via-telegram/27905/4

![image](https://user-images.githubusercontent.com/10910767/135732066-4c6c9998-7ab0-409d-8417-5075f92c35ad.png)

**Comment by OKDaG** [comment] 2021-10-03 07:53
That's strange, i also tried it without storing the image on the harddisc, same error. nodered ist running here as a docker container, fresh installation on two different systems (both hosts ubuntu 20.04 with docker 20.10.7 running nodered/node-red:latest@sha256:ddd05759e91dce9db82d36a3df66011936cc49d59ac329589df379c44e74867e).

and that's also weird, tried it on raspi without docker and it works.

[{"id":"96f77d076a52f9a7","type":"inject","z":"f6f2187d.f17ca8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":240,"wires":[["1b6e18b0c16520ba"]]},{"id":"1b6e18b0c16520ba","type":"http request","z":"f6f2187d.f17ca8","name":"","method":"GET","ret":"bin","paytoqs":"ignore","url":"https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg","tls":"","persist":false,"proxy":"","authType":"","x":340,"y":240,"wires":[["c018db46f8e21c08","3bbe515a2e0f8c10"]]},{"id":"3bbe515a2e0f8c10","type":"function","z":"f6f2187d.f17ca8","name":"","func":"\nvar pl = {\n content: msg.payload,\n type : 'photo',\n chatId: 27960xxxx\n}\n\nmsg.payload = pl;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":540,"y":240,"wires":[["90e8af0dac58027f","0e917861d78ecc2d"]]},{"id":"90e8af0dac58027f","type":"telegram sender","z":"f6f2187d.f17ca8","name":"","bot":"0385f759deab4c2f","haserroroutput":false,"outputs":1,"x":760,"y":240,"wires":[[]]},{"id":"c018db46f8e21c08","type":"image","z":"f6f2187d.f17ca8","name":"","width":160,"data":"payload","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":560,"y":300,"wires":[]},{"id":"0e917861d78ecc2d","type":"debug","z":"f6f2187d.f17ca8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":750,"y":200,"wires":[]},{"id":"0385f759deab4c2f","type":"telegram bot","botname":"nrbot.fra","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]

**Comment by windkh** [comment] 2021-10-03 13:31
Ah ok. So if you run inside docker you get the error in the sender node.
Maybe we can get the callstack either via the console of node-red or maybe in the second output see

[{"id":"97bf33986b5f261d","type":"inject","z":"89e16d21b4d07ec8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":200,"y":360,"wires":[["da8880f47da5782f"]]},{"id":"da8880f47da5782f","type":"http request","z":"89e16d21b4d07ec8","name":"","method":"GET","ret":"bin","paytoqs":"ignore","url":"https://upload.wikimedia.org/wikipedia/commons/3/3a/Cat03.jpg","tls":"","persist":false,"proxy":"","authType":"","x":400,"y":360,"wires":[["93060515c2cbc9af","f83b244d7eab6f7d"]]},{"id":"f83b244d7eab6f7d","type":"function","z":"89e16d21b4d07ec8","name":"","func":"\nvar pl = {\n content: msg.payload,\n type : 'photo',\n chatId: 27960xxxx\n}\n\nmsg.payload = pl;\n\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":600,"y":360,"wires":[["3b3301395ec8dd8d","7c392a3ea6058637"]]},{"id":"3b3301395ec8dd8d","type":"telegram sender","z":"89e16d21b4d07ec8","name":"","bot":"0385f759deab4c2f","haserroroutput":true,"outputs":2,"x":820,"y":360,"wires":[["09806b54e5e405fa"],["097f35116365c2a8"]]},{"id":"93060515c2cbc9af","type":"image","z":"89e16d21b4d07ec8","name":"","width":160,"data":"payload","dataType":"msg","thumbnail":false,"active":true,"pass":false,"outputs":0,"x":620,"y":420,"wires":[]},{"id":"7c392a3ea6058637","type":"debug","z":"89e16d21b4d07ec8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":810,"y":320,"wires":[]},{"id":"097f35116365c2a8","type":"debug","z":"89e16d21b4d07ec8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1010,"y":380,"wires":[]},{"id":"09806b54e5e405fa","type":"debug","z":"89e16d21b4d07ec8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1010,"y":340,"wires":[]},{"id":"0385f759deab4c2f","type":"telegram bot","botname":"nrbot.fra","usernames":"","chatids":"","baseapiurl":"","updatemode":"polling","pollinterval":"300","usesocks":false,"sockshost":"","socksport":"6667","socksusername":"anonymous","sockspassword":"","bothost":"","botpath":"","localbotport":"8443","publicbotport":"8443","privatekey":"","certificate":"","useselfsignedcertificate":false,"sslterminated":false,"verboselogging":false}]

**Comment by OKDaG** [comment] 2021-10-04 17:16
After reinstalling nodered and just install node-red-contrib-telegrambot the error is gone. Guess this is related to some other plugin. Will report which one if i found it.

**Comment by windkh** [comment] 2021-10-04 17:31
Good news… yes please keep me informed

**Comment by Speeedy0815** [comment] 2021-10-09 05:02
Hi @windkh,

I sent you both via mail.

Thank you for your fast answer.

**Comment by windkh** [comment] 2021-10-11 06:03
![image](https://user-images.githubusercontent.com/10910767/136740527-c6d50050-edd3-4a90-bb0b-fdf2de4eff7c.png)

You can try this and send me the output.
Please send me the image that you want to send via private email.

**Comment by windkh** [comment] 2021-12-05 19:40
is this still an issue or can I close it? @Speeedy0815

**Comment by Speeedy0815** [comment] 2021-12-06 07:13
Hi  @windkh,

I tryed it in Oktober after your mails. But it didn't work. 

But I can't try it anymore because I haven't installed node-red-contrib-telegrambot anymore.

I use now node-red-contrib-telegrambot-home. (But here i can also not send photos)

I don't know what is wrong here. By the way --> sending via mail is working..... 

So, thank you. You can close it.

**Closed** 2021-12-06 17:02 UTC
