### ISSUE TITLE
Multiple commands do not work with inline keyboard

### ISSUE THREAD

**Issue by aniston** [windkh/node-red-contrib-telegrambot#53] opened 2018-09-15 22:03 UTC
can multiple commands in the same flow work? in my example setting up 2 commands with keyboard (using the keyboard example) fails to execute the second or first command depending on which one was placed first in the flow. The problem is that the first command to receive the bot_command consumes the command and it does not reach the second command.

This seems to be because of the 2° output in the command node that picks up all commands even though not related to selected one , hence not allowing the correct command node to receive it.

As a suggestion can there be a tick flag in the command node to pick up all commands even those not related to its own command lookup, this will allow the right command node to pick up its own command.

**Comment by windkh** [comment] 2018-09-16 06:39
Hi thanks for reporting this... to be honest I never tried this. I will try to reproduce it.

**Comment by aniston** [comment] 2018-09-17 10:42
Hallo Karl,
forgot the most important part ! many thanks for making this library available :+1: 

and here is some more input and simple testing flow.

I made a separate simple flow to test and noticed that the problem of the _right command not getting picked up_ and noticed that the problem is not visible initially , modifying the flow does tend to show up the problem.

I could be doing something wrong so i'm not sure if this illustrated the issue, please let me know if I should be doing it another way. Test made with Telegram Desktop and Android Cell fone.
 
If possible I guess having a way to pick only the right bot_command or pass command over to the other node would help like in the "switch" case, till we reach the end and then fall over to a pick up all commands.

Here is the simple flow, in most cases for correct commands like /a and /b we should not be seeing the "False" debug output as both bot_command nodes  exist, only everything else (example /c) should show a "False" command.

`[{"id":"310f2c93.b03694","type":"telegram command","z":"e4e6273b.d66808","name":"/a","command":"/a","bot":"16909818.0f1d28","x":70,"y":60,"wires":[["285d6b2b.9f7db4"],["d3a47af8.7fbee8"]]},{"id":"d3a47af8.7fbee8","type":"debug","z":"e4e6273b.d66808","name":"A FALSE","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":240,"y":80,"wires":[]},{"id":"285d6b2b.9f7db4","type":"debug","z":"e4e6273b.d66808","name":"A TRUE","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":240,"y":40,"wires":[]},{"id":"e4c045a0.f87ed8","type":"telegram command","z":"e4e6273b.d66808","name":"/b","command":"/b","bot":"16909818.0f1d28","x":70,"y":160,"wires":[["406920e4.62dff"],["557b70b2.164e4"]]},{"id":"557b70b2.164e4","type":"debug","z":"e4e6273b.d66808","name":"B FALSE","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":240,"y":180,"wires":[]},{"id":"406920e4.62dff","type":"debug","z":"e4e6273b.d66808","name":"B TRUE","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":240,"y":140,"wires":[]},{"id":"16909818.0f1d28","type":"telegram bot","z":"","botname":"gcpbot","usernames":"","chatids":"","baseapiurl":"","pollinterval":"300"}]`

best regards,
Aniston

**Comment by aniston** [comment] 2018-09-17 10:57
Sorry, seems like my mistake, the multiple commands work if deployed with FULL Flow and does not work correctly if deployed in MODIFIED Flow mode, this is my last finding, sadly only now I thought of trying it out like that.

is there a reason for this behaviour ?

**Comment by windkh** [comment] 2018-09-18 20:13
I don't know why the MODIFIED deploy mode fails. This was reported before, but I could not find the reason for this. As your problem is solved I will close this issue.
have a nice day

**Closed by windkh** 2018-09-18 20:13 UTC
